phraseapp:
  project_id: "cc52f6727e3ef998f0f64ee3d2bdacda"
  file_format: "pot"
  pull:
    targets:
      - file: ./INSTALL/templates/install.pot
        params:
          file_format: po
  push:
    sources:
      - file: ./INSTALL/fr/install.po
        params:
          file_format: po