phraseapp:
  access_token: "ec4425a7c91f1976a6cf293ff8d95f0fd03069c3a7c5a7372a593fa33ad62051"
  project_id: "cc52f6727e3ef998f0f64ee3d2bdacda"
  file_format: "pot"
  push:
    sources:
      file: "./INSTALL/templates/install.pot"











