phraseapp:
  access_token: "d55403ed8e96cad67113"
  project_id: "cc52f6727e3ef998f0f64ee3d2bdacda"
  file_format: "pot"
  push:
    sources:
      file: "./INSTALL/templates/install.pot"











